version: "2"
services:
  one-network-integration-ui:
    image: openlmis/dev-ui:9.0.7
    ports:
      - "9000:9000"
      - "9876:9876"
    working_dir: /app
    volumes:
      - '.:/app'
    env_file: .env
    volumes_from:
      - auth-ui
      - ui-components
      - ui-layout
      - referencedata-ui
    depends_on:
      - auth-ui
      - ui-components
      - ui-layout
      - referencedata-ui
  auth-ui:
    image: openlmis/auth-ui:6.2.13
    volumes:
      - '/openlmis-auth-ui'
  ui-components:
    image: openlmis/ui-components:7.2.12
    volumes:
      - '/openlmis-ui-components'
  ui-layout:
    image: openlmis/ui-layout:5.2.6
    volumes:
      - '/openlmis-ui-layout'
  referencedata-ui:
    image: openlmis/referencedata-ui:5.6.13
    volumes:
      - '/openlmis-referencedata-ui'
  image:
    build: .
    image: openlmis/one-network-integration-ui
